name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチに変更があったときにデプロイが実行される

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the Docusaurus site
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        npm install --save gh-pages
        npx gh-pages -d build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
